name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2

    - name : Create and activate environment
      run :    python3 -m venv .venv && cd .venv/bin/ && sudo chmod +x ./activate && ./activate && cd ../../
    
    - name : Set password
      run : export SECRET=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7 && export PASSWORD=EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW
    
    - name : Install Packages 
      run : pip install -r requirements.txt
    
    - name : Run tests 
      run : pytest test.py
